#! /bin/sh

sxhkd &
/home/george/.config/polybar/launch.sh

bspc monitor -d I II III IV

bspc config bottom_padding 50
bspc config border_width 5
bspc config window_gap 16
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_pointer false
bspc config center_pseudo_tiled true
bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
bspc config normal_border_color \#1c1b1d
bspc config active_border_color \#dd0ce5
bspc config focused_border_color \#dd0ce5
bspc config presel_feedback_color \#6272a4 

bspc rule -a Docky layer=above manage=on border=off focus=off locked=on
bspc rule -a xfce4-notes floating=on
bspc rule -a Firefox desktop=^1 follow=on
bspc rule -a tellico desktop=^2 follow=on
bspc rule -a quassel desktop=^6 follow=on
bspc rule -a deluge desktop=^7 follow=on
bspc rule -a Spotify desktop=^2 follow=on
